
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/repostdb?serverTimezone=Asia/Seoul
    username: album2me
    password: ENC(NafMrdQSRzbJN+YK3qWHWQ==)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ENC(VY834y5nhBS8+gvjF0nWF9Bs/wV4AVcsSVqSj9iDvxI=)
      secret-key: ENC(FR8m+0neWo11YVjxtQl8qDzDb/OvUUHwqy1evCgNeVpMA5HVvqLWf7vzQnQ6FjO/d/mDVNFYmRg=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      url: https://s3.ap-northeast-2.amazonaws.com
      bucket: repost-bucket

jwt:
  token:
    header: Authorization
    issuer: album2me
    client-secret: ENC(UvtsKp8Ul3wLjWNtyKOf3w==)
    expirySeconds: 72000
