name: Java CI with Gradle

on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up JDK 17
        uses: actions/checkout@v3
      
      - name: JDK17을 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Gradle 명령 실행을 위한 권한 부여
        run: chmod +x gradlew

      - name: Gradle test를 실행 후 report 추출
        run: ./gradlew build jacocoTestReport
