name: Java CI with Gradle

on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql database: 'repostdb'
          mysql user: 'album2me'
          mysql password: ${{secrets.DB_PASSWORD}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        env:
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: ./gradlew test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
